/*
 * common.h
 *
 *  Created on: Apr 21, 2024
 *      Author: veins
 */

#ifndef COMMON_H_
#define COMMON_H_

// Enumeration types tracking the stage of protocol.
enum class CoinAssignmentStage {
    INIT,
    REQUESTED,
    SENT,
    FINISHED,
    FAILED
};

enum class CoinDepositStage {
    INIT,
    REQUESTED,
    SIGNATURE_REQUESTED,
    SIGNATURE_SENT,
    SUBMITTED,
    FINISHED,
    FAILED
};

#define RSU_ADDR 1025
#define RSU_POSITION_X 220
#define RSU_POSITION_Y 220

// Sizes of messages.
#define MSG_HEADER_SIZE 54 // overhead of TCP + IP + MAC
#define MSG_DATA_SIZE 200
#define COIN_REQUEST_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)
#define COIN_ASSIGNMENT_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)
#define COIN_DEPOSIT_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)
#define COIN_DEPOSIT_SIGNATURE_REQUEST_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)
#define COIN_SUBMISSION_BYTE_SIZE (MSG_DATA_SIZE + MSG_HEADER_SIZE)

// Computation workloads.
// TODO: Should be a model involving latencies and CPU loads.
#define COIN_REQUEST_LATENCY_MEAN 0.100
#define COIN_REQUEST_LATENCY_STDDEV 0.005
#define COIN_ASSIGNMENT_LATENCY_MEAN 2.000
#define COIN_ASSIGNMENT_LATENCY_STDDEV 0.005
#define COIN_DEPOSIT_LATENCY_MEAN 0.100
#define COIN_DEPOSIT_LATENCY_STDDEV 0.005
#define COIN_DEPOSIT_SIGNATURE_REQUEST_LATENCY_MEAN 2.000
#define COIN_DEPOSIT_SIGNATURE_REQUEST_LATENCY_STDDEV 0.005
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_LATENCY_MEAN 0.500
#define COIN_DEPOSIT_SIGNATURE_RESPONSE_LATENCY_STDDEV 0.005
#define COIN_SUBMISSION_LATENCY_MEAN 2.000
#define COIN_SUBMISSION_LATENCY_STDDEV 0.005

#endif
